name: Math-Utility Repo using using Maven, JUnit & CI (GitHub Actions) | © 2023 đoan.khanh

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18 - Mượn JDK 18 của server Mỹ
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven - Build app và chạy test case hoặc màu xanh hoặc nhận mail chửi
      run: mvn -B package --file pom.xml
      
    - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
      run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
    - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
      uses: actions/upload-artifact@v1
      with:
          name: nha-tuyen-dung-download-jar-o-day.zip # Đây là hyperlink download .jar .war ở bên Mỹ
          path: staging
